### ISSUE TITLE
Google Analytics GA4 support

### ISSUE THREAD

**Issue by avoinea** [kitconcept/volto-dsgvo-banner#9]
Does this add-on support Google Analytics GA4? As I can't see any traffic in Google Analytics

**Comment by avoinea** [comment]
Hmm :thinking: https://github.com/react-ga/react-ga/issues/493

**Comment by avoinea** [comment]
We have to upgrade to [react-ga4](https://www.npmjs.com/package/react-ga4)

**Comment by sneridagh** [comment]
merged in #10
